package:
  name: json-fortran
  version: "5.0.2" #{{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: https://github.com/jacobwilliams/json-fortran.git

requirements:
  build:
    - gcc-5
    - fobis.py