package:
  name: json-fortran
  version: 5.1.0 

source:
  #git_url: https://github.com/jacobwilliams/json-fortran.git
  url: https://github.com/jacobwilliams/json-fortran/archive/5.1.0.tar.gz
requirements:
  build:
    - gcc-5
    - fobis.py
