package:
  name: json-fortran
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: https://github.com/jacobwilliams/json-fortran.git

build:
  features:
    - ifort
    
requirements:
  build:
    - fobis.py